FROM node:13.5.0-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN yarn global add @angular/cli

COPY package.json package.json
COPY ngsw-config.json ngsw-config.json
RUN cd /usr/src/app/ && yarn install

ADD . /usr/src/app

EXPOSE 4200
EXPOSE 49153
