FROM node:12

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN yarn global add @angular/cli

COPY package.json package.json
RUN cd /usr/src/app/ && yarn install --frozen-lockfile

ADD . /usr/src/app

EXPOSE 4200
EXPOSE 49153
