ARG CLIENT_MODULES_BASE_IMAGE_NAME
ARG CLIENT_MODULES_BASE_IMAGE_TAG

FROM $CLIENT_MODULES_BASE_IMAGE_NAME:$CLIENT_MODULES_BASE_IMAGE_TAG

RUN npm run build:prod

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY dynamic-environments usr/dynamic-environments

COPY --from=builder /usr/src/app/dist/* /usr/share/nginx/html/
