FROM node:14-slim

WORKDIR /usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --prod

COPY angular.json angular.json
COPY tsconfig.json tsconfig.json
COPY ngsw-config.json ngsw-config.json

RUN yarn compile-ivy-dependencies

COPY src src

