FROM node:12

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN yarn install -g @angular/cli --loglevel error

COPY package.json package.json
RUN cd /usr/src/app/ && yarn install --frozen-lockfile

ADD . /usr/src/app

EXPOSE 4200
EXPOSE 49153
