FROM node:13-slim

WORKDIR /usr/src/app

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install --frozen-lockfile --prod

COPY angular.json angular.json
COPY tsconfig.json tsconfig.json
COPY ngsw-config.json ngsw-config.json

RUN yarn compile-ivy-dependencies

COPY src src
