pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - 'status-success=ci/circleci: retag-server-image'
      - 'status-success=ci/circleci: swap-client-config'
    actions:
      merge:
        method: merge
