version: "2"
services:
  e2e-tests:
    build:
      context: client
      dockerfile: DockerfileE2ETests
    container_name: montepouli-e2e-tests
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e
      - client-e2e
    command: sh -c 'npm run protractor'

  client-e2e:
    build:
      context: client
      dockerfile: DockerfileE2EClient
    container_name: montepouli-client-e2e
    ports:
      - "80"
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e

  server-e2e:
    build: server
    container_name: montepouli-server-e2e
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - SERVER_SECRET=secret01
      - ENV=dev
      - MONGO_DNS_NAME=mongodb-e2e
    ports:
      - "3000"
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - e2e
    command: sh -c 'npm run start:dev'

  mongodb-e2e:
    container_name: montepouli-mongodb-e2e
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017"
      - "28017"
    networks:
      - e2e

networks:
  e2e:
