FROM montepoeli.club/montepoeli-base-node-modules:latest

#bcrypt dependencies
RUN apt-get update && apt-get -y upgrade && apt-get -y install python3 make g++

WORKDIR usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY apps/api .

RUN npm run build

EXPOSE 3000
