FROM tjokvol/montepoeli-base-node-modules:latest

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

RUN npm run compile-ivy-dependencies

COPY apps/client apps/client

EXPOSE 4200
EXPOSE 49153
