FROM tjokvol/montepoeli-base-node-modules:latest

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

RUN npm run compile-ivy-dependencies

ADD apps/client /usr/src/app

EXPOSE 4200
EXPOSE 49153
