version: "2"
services:
  client-e2e-tests:
    build:
      context: client
      dockerfile: LocalDockerfile
    container_name: montepouli-client
    ports:
      - "4201:4200"
      - "49154:49153"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/angular.json:/usr/src/app/angular.json
      - ./client/tslint.json:/usr/src/app/tslint.json
    networks:
      - e2e
    depends_on:
      - server
      - mongodb
    command: bash -c 'npm run e2e:build-server'

  server:
    build: server
    container_name: montepouli-e2e-server
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - SERVER_SECRET=secret01
      - ENV=dev
    ports:
      - "3001:3001"
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - e2e
    command: sh -c 'npm run start:dev'

  mongodb:
    container_name: montepouli-e2e-mongo-db
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - montepouli-e2e-volume:/data/db
      - montepouli-e2e-volume:/data/configdb
    ports:
      - "27018:27017"
      - "28018:28017"
    networks:
      - e2e

networks:
  e2e:

volumes:
  montepouli-e2e-volume:
