version: "2"
services:
  e2e-tests:
    build: e2e
    container_name: montepouli-e2e-tests
    volumes:
      - ./e2e/reports/images:/root/target/screenshots
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e
      - client-e2e
      - selenium-hub
      - chrome
    command: sh -c 'sleep 10 && npm run protractor'
  
  webserver-e2e:
    image: nginx:mainline-alpine
    container_name: montepouli-webserver-e2e
    ports:
      - "443:443"
    volumes:
      - ./e2e/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - server-e2e
      - mongodb-e2e
      - client-e2e
    networks:
      - e2e
  
  client-e2e:
    image: ${CLIENT_BASE_IMAGE_NAME}:${CLIENT_BASE_IMAGE_TAG}
    container_name: montepouli-client-e2e
    ports:
      - "80:80"
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e

  client-e2e:
    image: ${CLIENT_BASE_IMAGE_NAME}:${CLIENT_BASE_IMAGE_TAG}
    container_name: montepouli-client-e2e
    ports:
      - "80:80"
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e

  server-e2e:
    image: ${SERVER_IMAGE_NAME}:${SERVER_IMAGE_TAG}
    container_name: montepouli-server-e2e
    environment:
      - SERVER_SECRET=secret01
      - ENV=prod
      - MONGO_DNS_NAME=mongodb-e2e
      - COOKIE_SECRET=secret
      - CORS_ORIGIN=https://www.webserver-e2e
      - DOMAIN=webserver-e2e
    ports:
      - "3000"
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - e2e
    depends_on:
      - mongodb-e2e
    command: sh -c 'sleep 3 && node dist/main.js'

  mongodb-e2e:
    container_name: montepouli-mongodb-e2e
    image: mongo:4.1
    ports:
      - "27017"
      - "28017"
    restart: always
    networks:
      - e2e

  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444"
    networks:
      - e2e

  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - e2e

  # firefox:
  #   image: selenium/node-firefox:3.141.59
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #   networks:
  #     - e2e

networks:
  e2e:
