version: "3.7"
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.local
    container_name: montepouli-client
    ports:
      - "4200:4200"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/angular.json:/usr/src/app/angular.json
      - ./client/tslint.json:/usr/src/app/tslint.json
    networks:
      - dev
    command: bash -c 'npm run start:dev-no-host'

  server:
    build:
      context: server
      dockerfile: Dockerfile.local
    container_name: montepouli-server
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - SERVER_SECRET=secret01
      - ENV=dev
      - MONGO_DNS_NAME=mongodb
      - COOKIE_SECRET=secret
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - dev
    command: sh -c 'npm run start:dev'

    
  mongodb:
    container_name: montepouli-mongo-db
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - montepouli-volume:/data/db
      - montepouli-volume:/data/configdb
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - dev

networks:
  dev:

volumes:
  montepouli-volume:

