version: "2"
services:
  e2e-tests:
    build: e2e
    container_name: montepouli-e2e-tests
    volumes:
      - ./e2e/reports/images:/usr/src/app/reports/screenshots
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e
      - client-e2e
      - selenium-hub
    command: sh -c 'npm run protractor'

  client-e2e:
    build:
      context: client
      dockerfile: client/Dockerfile.configured
      args:
        CLIENT_BASE_IMAGE_NAME: ${CLIENT_BASE_IMAGE_NAME}
        CLIENT_BASE_IMAGE_TAG: ${CLIENT_BASE_IMAGE_TAG}
        CLIENT_TYPE: ${CLIENT_TYPE}
    container_name: montepouli-client-e2e
    ports:
      - "80"
    networks:
      - e2e
    depends_on:
      - server-e2e
      - mongodb-e2e

  server-e2e:
    image: ${SERVER_IMAGE_NAME}:${SERVER_IMAGE_TAG}
    container_name: montepouli-server-e2e
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - SERVER_SECRET=secret01
      - ENV=dev
      - MONGO_DNS_NAME=mongodb-e2e
    ports:
      - "3000"
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - e2e
    command: sh -c 'npm run start:dev'

  mongodb-e2e:
    container_name: montepouli-mongodb-e2e
    image: mongo:4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017"
      - "28017"
    networks:
      - e2e

  selenium-hub:
    image: selenium/hub:3.141.59-titanium
    container_name: selenium-hub
    ports:
      - "4444"
    networks:
      - e2e

  chrome:
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - e2e

  firefox:
    image: selenium/node-firefox:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - e2e

networks:
  e2e:
