FROM node:13

WORKDIR /usr/src/app

COPY . .

RUN npm install

# RUN apt-get update && apt-get -y upgrade && apt-get -y install python3 make g++

RUN apt-get update && apt-get install git -y

RUN npm run affected:apps

RUN npm run affected:apps

