pull_request_rules:

  - name: automatic merge depfu on successfull e2e tests
    conditions:
      - 'status-success=ci/circleci: e2e-tests'
      - 'head~=depfu*'
    actions:
      merge:
        method: merge
  
  - name: automatic merge depfu on e2e tests and client base rebuild
    conditions:
      - 'status-success=ci/circleci: rebuild-client-base'
      - 'head~=depfu/batch_all/client*'
    actions:
      merge:
        method: merge

  - name: automatic merge dependabot on successfull e2e tests
    conditions:
      - 'status-success=ci/circleci: e2e-tests'
      - 'head~=dependabot*'
    actions:
      merge:
        method: merge
    
