pull_request_rules:
  - name: successfull e2e tests and rebuild of basefor depfu branches
    conditions:
      - 'status-success=ci/circleci: e2e-tests'
      - 'status-success=ci/circleci: rebuild-base'
      - 'head~=depfu*'
    actions:
      merge:
        method: merge

  - name: automatic merge dependabot on successfull e2e tests
    conditions:
      - 'status-success=ci/circleci: e2e-tests'
      - 'head~=dependabot*'
    actions:
      merge:
        method: merge
