# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/node:11

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true

    - run: |
        cd client
        CLIENT_TAG=0.1
        IMAGE_CLIENT_NAME=montepouli-client
        docker build -t $DOMAIN/$IMAGE_CLIENT_NAME:$CLIENT_TAG .
        docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOMAIN/$IMAGE_CLIENT_NAME:$CLIENT_TAG

    - run: |
        cd server
        SERVER_TAG=0.1
        IMAGE_SERVER_NAME=montepouli-server
        docker build -t $DOMAIN/$IMAGE_SERVER_NAME:$SERVER_TAG .
        docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOMAIN/$IMAGE_SERVER_NAME:$SERVER_TAG

    - run: |
        cd client
        STORYBOOK_TAG=0.1
        IMAGE_STORYBOOK_NAME=montepouli-storybook
        docker build -f StorybookDockerfile -t $DOMAIN/$IMAGE_STORYBOOK_NAME:$STORYBOOK_TAG .
        docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOMAIN/$IMAGE_STORYBOOK_NAME:$STORYBOOK_TAG

#      # Download and cache dependencies
#    - restore_cache:
#        keys:
#        - v1-dependencies-{{ checksum "client/package.json" }}
#
#    - run: cd client && npm install
#
#    - save_cache:
#        paths:
#          - client/node_modules
#        key: v1-dependencies-{{ checksum "client/package.json" }}
#
#    - restore_cache:
#        keys:
#          - v1-dependencies-{{ checksum "server/package.json" }}
#
#    - run: cd server && npm install
#
#    - save_cache:
#        paths:
#        - server/node_modules
#        key: v1-dependencies-{{ checksum "server/package.json" }}
#
#    # run tests!
#    - run: cd client && npm test
#    - run: cd server && npm run pretest && npm test
#
#    - setup_remote_docker
#    - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#
#    - run: docker build . -t montepoeli
#
#    - run: docker tag montepoeli tjokvol/montepoeli:bundle
#
#    - run: docker push tjokvol/montepoeli:bundle

