# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/node:11

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout
    - setup_remote_docker

    - run: |
        TAG=0.1.$CIRCLE_BUILD_NUM
        docker build -t $DOMAIN/$IMAGE_NAME:$TAG .
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push $DOMAIN/$IMAGE_NAME:$TAG

#      # Download and cache dependencies
#    - restore_cache:
#        keys:
#        - v1-dependencies-{{ checksum "client/package.json" }}
#
#    - run: cd client && npm install
#
#    - save_cache:
#        paths:
#          - client/node_modules
#        key: v1-dependencies-{{ checksum "client/package.json" }}
#
#    - restore_cache:
#        keys:
#          - v1-dependencies-{{ checksum "server/package.json" }}
#
#    - run: cd server && npm install
#
#    - save_cache:
#        paths:
#        - server/node_modules
#        key: v1-dependencies-{{ checksum "server/package.json" }}
#
#    # run tests!
#    - run: cd client && npm test
#    - run: cd server && npm run pretest && npm test
#
#    - setup_remote_docker
#    - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#
#    - run: docker build . -t montepoeli
#
#    - run: docker tag montepoeli tjokvol/montepoeli:bundle
#
#    - run: docker push tjokvol/montepoeli:bundle

