version: 2
jobs:
  save-version:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            grep '"version":' package.json | cut -d\" -f4 > /tmp/version-$CIRCLE_WORKFLOW_ID.txt

      - store_artifacts:
          path: /tmp/version-$CIRCLE_WORKFLOW_ID.txt

          command: |
            cat /tmp/version-$CIRCLE_WORKFLOW_ID.txt

      - persist_to_workspace:
            root: /tmp
            paths:
              - version-$CIRCLE_WORKFLOW_ID.txt

  build-client-base:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: /tmp/workspace

      - run:
          command: |
            cat /tmp/workspace/version-$CIRCLE_WORKFLOW_ID.txt
            CLIENT_TAG=$CIRCLE_PR_NUMBER
            IMAGE_CLIENT_NAME=montepouli-client
            cd client
            docker build -t $DOMAIN/$IMAGE_CLIENT_NAME:$CLIENT_TAG .

      - deploy:
          command: |
            CLIENT_TAG=$CIRCLE_PR_NUMBER
            IMAGE_CLIENT_NAME=montepouli-client
            docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOMAIN/$IMAGE_CLIENT_NAME:$CLIENT_TAG

  build-server:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: /tmp/workspace

      - run: |
          cd server
          SERVER_TAG=$CIRCLE_PR_NUMBER
          echo $SERVER_TAG
          echo $CIRCLE_WORKFLOW_ID
          IMAGE_SERVER_NAME=montepouli-server
          docker build -t $DOMAIN/$IMAGE_SERVER_NAME:$SERVER_TAG .

      - deploy:
          command: |
            SERVER_TAG=$CIRCLE_PR_NUMBER
            IMAGE_SERVER_NAME=montepouli-server
            docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOMAIN/$IMAGE_SERVER_NAME:$SERVER_TAG

  swap-client-config-e2e:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: /tmp/workspace

      - run:
          command: |
            docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD

      - run:
          command: |
            cd client
            CLIENT_TAG=$CIRCLE_PR_NUMBER
            IMAGE_CLIENT_NAME=montepouli-client-e2e
            docker build -f Dockerfile.configured . -t $DOMAIN/$IMAGE_CLIENT_NAME:$CLIENT_TAG --build-arg CLIENT_BASE_IMAGE_NAME=montepoeli.club/montepouli-client --build-arg CLIENT_BASE_IMAGE_TAG=$CIRCLE_PR_NUMBER --build-arg CLIENT_TYPE=e2e

      - deploy:
          command: |
            CLIENT_TAG=$CIRCLE_PR_NUMBER
            IMAGE_CLIENT_NAME=montepouli-client-e2e
            docker push $DOMAIN/$IMAGE_CLIENT_NAME:$CLIENT_TAG

  build-storybook:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: /tmp/workspace

      - run: |
          cd client
          STORYBOOK_TAG=1.0
          IMAGE_STORYBOOK_NAME=montepouli-storybook
          docker build -f Dockerfile.storybook -t $DOMAIN/$IMAGE_STORYBOOK_NAME:$STORYBOOK_TAG .

      - deploy:
          command: |
            cd client
            STORYBOOK_TAG=1.0
            IMAGE_STORYBOOK_NAME=montepouli-storybook

            docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOMAIN/$IMAGE_STORYBOOK_NAME:$STORYBOOK_TAG

  e2e-test:
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/repo
    environment:
      - CLIENT_BASE_IMAGE_NAME: montepoeli.club/montepouli-client-e2e
      - CLIENT_BASE_IMAGE_TAG: $CIRCLE_PR_NUMBER
      - SERVER_IMAGE_NAME: montepoeli.club/montepouli-server
      - SERVER_IMAGE_TAG: $CIRCLE_PR_NUMBER
      - CLIENT_TYPE: e2e
    steps:
      - checkout
      - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - run: sudo chmod +x /usr/local/bin/docker-compose
      - run: docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: npm run start:e2e-environment-build-server

  swap-client-config:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: /tmp/workspace

      - run:
          command: |
            docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD

      - run:
          command: |
            cd client
            IMAGE_CLIENT_NAME=montepouli-client
            TESTED_CLIENT_TAG=$CIRCLE_WORKFLOW_ID-e2e
            docker build -f Dockerfile.configured -t $DOMAIN/$IMAGE_CLIENT_NAME:$TESTED_CLIENT_TAG . --build-arg CLIENT_BASE_IMAGE_NAME=montepoeli.club/montepouli-client-e2e --build-arg CLIENT_BASE_IMAGE_TAG=$CIRCLE_WORKFLOW_ID --build-arg CLIENT_TYPE=server

      - deploy:
          command: |
            TESTED_CLIENT_TAG=$CIRCLE_WORKFLOW_ID-e2e
            IMAGE_CLIENT_NAME=montepouli-client
            docker push $DOMAIN/$IMAGE_CLIENT_NAME:$TESTED_CLIENT_TAG

  retag-server-image:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker login https://montepoeli.club -u $DOCKER_USER -p $DOCKER_PASSWORD

      - run: |
          SERVER_TAG=$CIRCLE_WORKFLOW_ID
          IMAGE_SERVER_NAME=montepouli-server
          TESTED_SERVER_TAG=$CIRCLE_WORKFLOW_ID-e2e

          docker pull $DOMAIN/$IMAGE_SERVER_NAME:$SERVER_TAG
          docker tag $DOMAIN/$IMAGE_SERVER_NAME:$SERVER_TAG $DOMAIN/$IMAGE_SERVER_NAME:$TESTED_SERVER_TAG

      - deploy:
          command: |
            TESTED_SERVER_TAG=$CIRCLE_WORKFLOW_ID-e2e
            IMAGE_SERVER_NAME=montepouli-server

            docker push $DOMAIN/$IMAGE_SERVER_NAME:$TESTED_SERVER_TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - save-version
      - build-client-base:
          requires:
            - save-version
      - build-server:
          requires:
            - save-version
      - swap-client-config-e2e:
          requires:
            - build-client-base
      - e2e-test:
          requires:
            - swap-client-config-e2e
            - build-server
      - build-storybook:
          filters:
            branches:
              only:
                - /feature-.*/
      - swap-client-config:
          requires:
            - build-client-base
            - e2e-test
          filters:
            branches:
              only: master
      - retag-server-image:
          requires:
            - e2e-test
          filters:
            branches:
              only: master
