FROM node:13-slim

#bcrypt dependencies
RUN apt-get update && apt-get -y upgrade && apt-get -y install python3 make g++

WORKDIR usr/src/app

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install --frozen-lockfile

COPY . .

RUN npm run build

EXPOSE 3000
