FROM node:14-slim

#bcrypt dependencies
RUN apt-get update && apt-get -y upgrade && apt-get -y install python3 make g++

WORKDIR usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000
