FROM node:12-slim as builder

# bcrypt dependencies
RUN apt-get update && apt-get -y upgrade && apt-get -y install python3 make g++

WORKDIR /usr/src/app

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install --frozen-lockfile --prod

COPY src src
COPY tsconfig.json tsconfig.json
COPY tsconfig.build.json tsconfig.build.json

RUN npm run build

FROM node:12-slim

COPY --from=builder /usr/src/app /

EXPOSE 3000
